"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
load_dotenv()
import sys



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m^m)*7k!7op-$lbw(7jd^yg$b2+dwcy9eh%jn=x1=id9vcrwt%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # подключаем ещё приложения
    'django.contrib.sites',
    'django.contrib.flatpages',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.yandex',
    'fpages',
    'news.apps.NewsConfig',
    'django_filters',
    'sign',
    'protect',
    'appointments.apps.AppointmentsConfig',
    'django_apscheduler' #периодические задачи
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    "allauth.account.middleware.AccountMiddleware",

    #     # Для кэширования всего сайта целиком
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS =[os.path.join(BASE_DIR, 'static')]
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATICFILES_DIRS = [
#     BASE_DIR / "static"
# ]


# LOGIN_URL = 'sign/login/'
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/about/'

# Подключение allauth------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

#-----------------------------------------------------


ACCOUNT_SIGNUP_FIELDS = ['username*','email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_METHODS = ['email']
# ACCOUNT_EMAIL_VERIFICATION = 'none'

ACCOUNT_SESSION_REMEMBER =True  # Чтобы убрать кнопку запомнить меня

# ACCOUNT_FORMS = {'signup': 'sign.models.BasicSignupForm'}  # Настройки для добавления в группы
ACCOUNT_FORMS = {'signup': 'sign.forms.MyCustomSignupForm'}  # Настройки для добавления в группы

# ACCOUNT_CONFIRM_EMAIL_ON_GET = True   # Подтверждение письма простым кликом по ссылке
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # Обязательное подтверждение по email

#-----------------------------------------------------

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'APP': {
            'client_id': os.getenv('YANDEX_CLIENT_ID'),
            'secret': os.getenv('YANDEX_SECRET'),
            'key': ''
        }
    }
}


#________________________________________________________________________________
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # через консоль проверяем отправку писем на почту
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # отправкa писем на почту

# Настройка почты для отправки писем
EMAIL_HOST = 'smtp.yandex.ru'  # адрес сервера Яндекс-почты для всех один и тот же
EMAIL_PORT = 465  # порт smtp сервера тоже одинаковый
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # ваше имя пользователя, например, если ваша почта user@yandex.ru, то сюда надо писать user, иными словами, это всё то что идёт до собаки
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASS')  # пароль от почты
EMAIL_USE_SSL = True  # Яндекс использует ssl, подробнее о том, что это, почитайте в дополнительных источниках, но включать его здесь обязательно
DEFAULT_FROM_EMAIL=EMAIL_HOST_USER+'@yandex.ru'
 #_______________________________________________________________________________________________

SITE_URL = "http://127.0.0.1:8000"

# Настройки рассылки админам
ADMINS = [
    ('Наталья', 'n.sh.ru'),
    # список всех админов в формате ('имя', 'их почта')
]

MANAGERS = [
    ('Н. Ш.', 'il.ru'),
    ('Н. Ш1.', 'ok.com'),
]

SERVER_EMAIL = DEFAULT_FROM_EMAIL  # это будет у нас вместо аргумента FROM в массовой рассылке

# формат даты, которую будет воспринимать наш задачник (вспоминаем модуль по фильтрам)
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"

# если задача не выполняется за 25 секунд, то она автоматически снимается, можете поставить время побольше, но как правило, это сильно бьёт по производительности сервера
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

# Настройки для celery, redis __________________
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/1'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
#------------------------------------------
#
# #  Кеширование
# CACHES = {
#     'default': {
#         # 'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         # 'LOCATION': os.path.join(BASE_DIR, 'cache_files'), # Указываем, куда будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
#         # # # Для кэширования всего сайта целиком
#         # # 'TIMEOUT': 60, # добавляем стандартное время ожидания в минуту (по умолчанию это 5 минут — 300 секунд)
#     # Для кэширования в редис нужно установить pip install django-redis и добавить настройки:
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://localhost:6379/2',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }
#_________________________________________________________


# Kод настройки логирования___________________________

# Создаем директорию для логов
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

# Настройки почты для отправки ошибок заданы выше.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        # ========== ФОРМАТТЕРЫ ДЛЯ КОНСОЛИ ==========

        # Для DEBUG и INFO: время, уровень, сообщение
        'console_debug_info': {
            'format': '{asctime} [{levelname}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Для WARNING и выше: + путь к источнику
        'console_warning': {
            'format': '{asctime} [{levelname}] {pathname}:{lineno} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Для ERROR и CRITICAL: + стек ошибки
        'console_error': {
            'format': '{asctime} [{levelname}] {pathname}:{lineno}\n{message}\n{exc_info}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # ========== ФОРМАТТЕРЫ ДЛЯ ФАЙЛОВ ==========

        # Для general.log: время, уровень, модуль, сообщение
        'file_general': {
            'format': '{asctime} [{levelname}] {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Для errors.log: время, уровень, сообщение, путь, стек ошибки
        'file_errors': {
            'format': '{asctime} [{levelname}] {pathname}:{lineno}\n{message}\n{exc_info}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Для security.log: время, уровень, модуль, сообщение
        'file_security': {
            'format': '{asctime} [{levelname}] {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

        # Для почты: время, уровень, сообщение, путь (без стека)
        'mail_admins': {
            'format': '{asctime} [{levelname}] {pathname}:{lineno}\n{message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    'filters': {
        # Фильтр: только при DEBUG=True
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },

        # Фильтр: только при DEBUG=False
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },

        # Фильтр: только ERROR и CRITICAL
        'error_critical_only': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.levelno >= 40,  # ERROR=40, CRITICAL=50
        },

        # Фильтр: только для определенных логгеров (errors.log)
        'errors_from_specific_loggers': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: (
                record.levelno >= 40 and  # ERROR или CRITICAL
                record.name in [  # И из определенных логгеров
                    'django.request',
                    'django.server',
                    'django.template',
                    'django.db.backends'
                ]
            ),
        },

        # Фильтр: только django.security (security.log)
        'security_only': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: record.name == 'django.security',
        },

        # Фильтр: ERROR и выше из django.request и django.server (для почты)
        'mail_admins_filter': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: (
                record.levelno >= 40 and  # ERROR или CRITICAL
                record.name in ['django.request', 'django.server']  # Только эти логгеры
            ),
        },
    },

    'handlers': {
        # ========== КОНСОЛЬНЫЕ ОБРАБОТЧИКИ ==========

        # DEBUG и INFO сообщения в консоль
        'console_debug_info': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'console_debug_info',
            'filters': ['require_debug_true'],  # Только при DEBUG=True
        },

        # WARNING сообщения в консоль (с путем)
        'console_warning': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
            'formatter': 'console_warning',
            'filters': ['require_debug_true'],  # Только при DEBUG=True
        },

        # ERROR и CRITICAL сообщения в консоль (со стеком)
        'console_error': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'stream': sys.stderr,
            'formatter': 'console_error',
            'filters': ['require_debug_true'],  # Только при DEBUG=True
        },

        # ========== ФАЙЛОВЫЕ ОБРАБОТЧИКИ ==========

        # general.log - INFO и выше
        'file_general': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'general.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'file_general',
            'filters': ['require_debug_false'],  # Только при DEBUG=False
            'encoding': 'utf-8',
        },

        # errors.log - ERROR и CRITICAL из определенных логгеров
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'errors.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'file_errors',
            'filters': ['errors_from_specific_loggers'],  # Фильтр по логгерам
            'encoding': 'utf-8',
        },

        # security.log - только django.security
        'file_security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'security.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 20,  # Храним дольше
            'formatter': 'file_security',
            'filters': ['security_only'],  # Только django.security
            'encoding': 'utf-8',
        },

        # ========== ПОЧТОВЫЙ ОБРАБОТЧИК ==========

        # Отправка на почту
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mail_admins',  # Без стека ошибок
            'filters': ['require_debug_false', 'mail_admins_filter'],  # DEBUG=False + фильтр логгеров
            'include_html': False,
        },
    },

    'loggers': {
        # ========== ОСНОВНЫЕ ЛОГГЕРЫ DJANGO ==========

        # django.request - логи запросов
        'django.request': {
            'handlers': [
                'console_debug_info', 'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_errors',  # errors.log
                'mail_admins',  # Почта (DEBUG=False)
            ],
            'level': 'DEBUG',
            'propagate': False,
        },

        # django.server - логи сервера разработки
        'django.server': {
            'handlers': [
                'console_debug_info', 'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_errors',  # errors.log
                'mail_admins',  # Почта (DEBUG=False)
            ],
            'level': 'INFO',
            'propagate': False,
        },

        # django.template - логи шаблонов
        'django.template': {
            'handlers': [
                'console_debug_info', 'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_errors',  # errors.log
            ],
            'level': 'INFO',
            'propagate': False,
        },

        # django.db.backends - логи базы данных
        'django.db.backends': {
            'handlers': [
                'console_debug_info',  # Консоль SQL (DEBUG=True)
                'file_errors',  # errors.log (только ошибки)
            ],
            'level': 'DEBUG',
            'propagate': False,
        },

        # django.security - логи безопасности
        'django.security': {
            'handlers': [
                'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_security',  # security.log
            ],
            'level': 'WARNING',
            'propagate': False,
        },

        # ========== ОСНОВНОЙ ЛОГГЕР DJANGO ==========

        # Основной логгер Django (все остальное)
        'django': {
            'handlers': [
                'console_debug_info', 'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_general',  # general.log (DEBUG=False)
            ],
            'level': 'INFO',
            'propagate': False,
        },

        # ========== КОРНЕВОЙ ЛОГГЕР ==========

        # Корневой логгер для всех приложений
        '': {
            'handlers': [
                'console_debug_info', 'console_warning', 'console_error',  # Консоль (DEBUG=True)
                'file_general',  # general.log (DEBUG=False)
            ],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

#___________________________________________________________________________________________________