# Generated by Django 5.2.7 on 2026-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_or_news',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='AR', verbose_name='Тип записи'),
        ),
    ]
