# Generated by Django 5.2.7 on 2026-01-28 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_categories', to=settings.AUTH_USER_MODEL, verbose_name='Подписки на категории'),
        ),
    ]
