# Generated by Django 5.2.7 on 2026-02-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorys',
            field=models.ManyToManyField(related_name='categories_post', through='news.PostCategory', to='news.category', verbose_name='Категории'),
        ),
    ]
